### ISSUE TITLE
Configurable Maximum Steam Output

### ISSUE THREAD

**Issue by necrogami** [erogenousbeef-zz/BigReactors#461]
I'd like to beable to configure in my pack the maximum steam output a reactor can make. I'd like to beable to configure above or below the current 50 B/t max.

**Comment by erogenousbeef** [comment]
I'm not clear exactly what you're requesting. Are you asking that the reactor be limited to a certain power output? Are you asking that the reactor only be allowed to pump out X amount of steam, regardless of how much it produces? Are you asking that, regardless of power output, the reactor be capped to produce X steam per tick?

In the first case, you can limit a reactor's size in the config and use the `powerProductionMultiplier` config setting to adjust the maximum theoretically-attainable power output.

The other two cases don't seem to make much sense. I'll need more explanation.

**Comment by Frontrider** [comment]
If i get it right, the variable you say is the thing what he needs, if it affects steam production.

**Comment by necrogami** [comment]
On this line https://github.com/erogenousbeef/BigReactors/blob/d54085cd53d0604ae216d7e31b8c2fb9e1184b13/src/main/java/erogenousbeef/bigreactors/common/multiblock/MultiblockReactor.java#L1049

You've hardcoded the maximum steam output of a reactor to 50buckets i was wondering if this could be made a configurable value.

**Comment by erogenousbeef** [comment]
Ah, you mean the size of the steam container. Yes, that's pretty easy. I'll get it done for the next patch release.
